version: "3.7"

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: yarn dev
    networks:
      - common
    env_file:
      - .env
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - common

networks:
  common:
